openapi: 3.0.1
info:
  title: Waves API
  description: |
    API for the new Waves text-to-speech model.
    Currently featuring our two models, Lightning & Lightning Large, with more models coming soon.
  version: 1.0.0
servers:
  - url: https://waves-api.smallest.ai
    description: Waves API server

paths:
  /api/v1/{model}/get_speech:
    post:
      summary: Get synthesized speech from text
      description: Fetch synthesized speech for a given text using the specified model, voice, and sample rate.
      operationId: getWavesSpeech
      parameters:
        - in: path
          name: model
          required: true
          schema:
            type: string
            enum: [lightning, lightning-large]
          description: The model to use for speech synthesis.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                voice_id:
                  type: string
                  description: Voice ID for the model.
                text:
                  type: string
                  description: The text to be synthesized into speech.
                speed:
                  type: number
                  minimum: 0.5
                  maximum: 2
                  default: 1
                  description: The speed for generated speech, Allowed range 0.5 - 2.
                sample_rate:
                  type: integer
                  default: 24000
                  enum: [8000, 16000, 24000]
                  description: Sample rate of the output audio file. Allowed values are 8000, 16000, or 24000.
                add_wav_header:
                  type: boolean
                  default: true
                  description: Whether to add a WAV header or not
              required:
                - voice_id
                - text
      responses:
        '200':
          description: Synthesized speech retrieved successfully.
          content:
            audio/wav:
              schema:
                type: string
                format: binary
                description: A PCM int16 WAV file at the specified frequency.
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error type
                  message:
                    type: string
                    description: Error message
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error type
                  message:
                    type: string
                    description: Error message
        '500':
          description: Server error occurred
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error type
                  message:
                    type: string
                    description: Error message
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
